//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjNotesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabNote
    {
        public int number { get; set; }
        public string title { get; set; }
        public string contents { get; set; }
        public int userid { get; set; }
    
        public virtual tabLogin tabLogin { get; set; }
    }
}
